/** FE가 생성하거나 분기에 쓰는 API 에러 코드. BE 임의 코드는 string으로 둔다. */
export const API_ERROR_CODE = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  TIMEOUT: 'TIMEOUT',
  NETWORK_ERROR: 'NETWORK_ERROR',
  INVALID_RESPONSE: 'INVALID_RESPONSE',
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_KEYWORD: 'INVALID_KEYWORD',
  ADDRESS_SEARCH_FAILED: 'ADDRESS_SEARCH_FAILED',
  INVALID_SSE_EVENT: 'INVALID_SSE_EVENT',
  SSE_STREAM_UNAVAILABLE: 'SSE_STREAM_UNAVAILABLE',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  INVALID_PASSWORD_FORMAT: 'INVALID_PASSWORD_FORMAT',
  ALREADY_LEFT: 'ALREADY_LEFT',
  REQUEST_ALREADY_SUBMITTED: 'REQUEST_ALREADY_SUBMITTED',
  ESTIMATE_REQUEST_NOT_SUBMITTED: 'ESTIMATE_REQUEST_NOT_SUBMITTED',
  DESIGNATED_ALREADY_EXISTS: 'DESIGNATED_ALREADY_EXISTS',
  QUOTE_ALREADY_RECEIVED_FROM_MOVER: 'QUOTE_ALREADY_RECEIVED_FROM_MOVER',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  ACTIVE_REQUEST_EXISTS: 'ACTIVE_REQUEST_EXISTS',
  MOVER_NOT_FOUND: 'MOVER_NOT_FOUND',
  USER_TYPE_MISMATCH: 'USER_TYPE_MISMATCH',
  KAKAO_EMAIL_REQUIRED: 'KAKAO_EMAIL_REQUIRED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODE)[keyof typeof API_ERROR_CODE];
